SELECT ENAME, JOB
FROM EMP
WHERE JOB = (SELECT JOB
  FROM EMP
  WHERE ENAME = 'MILLER' AND SAL > (SELECT SAL
  FROM EMP
  WHERE ENAME = 'JAMES' AND HIREDATE > (SELECT HIREDATE
  FROM EMP
  WHERE ENAME = 'KING' AND DEPTNO = (SELECT DEPTNO
  FROM DEPT
  WHERE DNAME = 'ACCOUNTING'))));
