SELECT DNAME
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
  FROM EMP
  WHERE SAL = (SELECT MAX(SAL)
  FROM EMP
  WHERE SAL < (SELECT MAX(SAL)
  FROM EMP
  WHERE SAL < (SELECT MAX(SAL)
  FROM EMP
  WHERE SAL < (SELECT MAX(SAL)
  FROM EMP)))));
